/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.tecnopotify.swing;

/**
 *
 * @author diego-lucia
 */
public class agregarTemaJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form agregarTemaJInternalFrame
     */
    
    /*    El caso de uso comienza cuando el administrador desea agregar
    un nuevo tema a una lista de reproducción. Para ello indica el
    usuario y la lista a la cual se agregará el tema, o sólo el nombre
    de la lista en caso de ser una lista por defecto. Luego, selecciona
    un tema (según sea de una lista propietaria pública, por defecto,
    o de un álbum) y el sistema lo agrega a la lista.*/
    public agregarTemaJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
