/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.tecnopotify.swing;

import edu.tecnopotify.entidades.Cliente;
import edu.tecnopotify.entidades.Genero;
import edu.tecnopotify.fabrica.Fabrica;
import edu.tecnopotify.interfaces.IControlador;
import static edu.tecnopotify.swing.consultarArtistaJInternalFrame.openFrameCount;
import static edu.tecnopotify.swing.consultarArtistaJInternalFrame.yOffset;
import static edu.tecnopotify.swing.consultarClienteJInternalFrame.xOffset;
import java.util.List;

/**
 *
 * @author menan
 */
public class ConsultaListaReproduccionJInternalFrame extends javax.swing.JInternalFrame {

    static int openFrameCount = 0;
    static final int xOffset = 30, yOffset = 30;
    private String path;
    IControlador crl;
    
    public ConsultaListaReproduccionJInternalFrame() {
        super("Consultar Cliente",
                true, //resizable
                true, //closable
                true, //maximizable
                true);//iconifiable
        //...Create the GUI and put it in the window...
        //...Then set the window size or call pack...

        //Set the window's location.
        setLocation(xOffset * openFrameCount, yOffset * openFrameCount);
        initComponents();
        this.setTitle("Consultar cliente");
        this.jLabelMostrarImagen.setVisible(true);
        Fabrica fabrica = Fabrica.getInstance();
        crl = fabrica.getInstancia();
        
        if (jCheckBoxListaDefecto.isSelected()) {
            //listar las listas por defecto del genero seleccionado
            List<Genero> generos = crl.mostrarListaGenero();
            for (Genero gen : generos) {
                jComboBoxNickname.addItem(gen.getNombre());
            }
            crl.mostrarListaGenero().get(jComboBoxNickname.getSelectedIndex());
        } else {//mostrar las listas del cliente
            List<Cliente> clientes = crl.listarClientes();
            for (Cliente cli : clientes) {
                jComboBoxNickname.addItem(cli.getNombre());
            }
            crl.listarClientes().get(jComboBoxNickname.getSelectedIndex());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelListaPorDefecto = new javax.swing.JLabel();
        jLabelMostrarImagen = new javax.swing.JLabel();
        jLabelListaPorDefecto1 = new javax.swing.JLabel();
        jComboBoxNickname = new javax.swing.JComboBox();
        jLabelListaPorDefecto2 = new javax.swing.JLabel();
        jCheckBoxListaDefecto = new javax.swing.JCheckBox();

        jLabelListaPorDefecto.setText("Lista por defecto");

        jLabelListaPorDefecto1.setText("Imagen");

        jLabelListaPorDefecto2.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListaPorDefecto)
                    .addComponent(jLabelListaPorDefecto1)
                    .addComponent(jLabelListaPorDefecto2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMostrarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxListaDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListaPorDefecto)
                    .addComponent(jCheckBoxListaDefecto))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListaPorDefecto2))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListaPorDefecto1)
                    .addComponent(jLabelMostrarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxListaDefecto;
    private javax.swing.JComboBox<String> jComboBoxNickname;
    private javax.swing.JLabel jLabelListaPorDefecto;
    private javax.swing.JLabel jLabelListaPorDefecto1;
    private javax.swing.JLabel jLabelListaPorDefecto2;
    private javax.swing.JLabel jLabelMostrarImagen;
    // End of variables declaration//GEN-END:variables
}
