/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.tecnopotify.swing;

import edu.tecnopotify.entidades.Cliente;
import edu.tecnopotify.entidades.ListaParticular;
import edu.tecnopotify.fabrica.Fabrica;
import edu.tecnopotify.interfaces.IControlador;
import static edu.tecnopotify.swing.AltaClienteJInternalFrame.openFrameCount;
import static edu.tecnopotify.swing.AltaClienteJInternalFrame.yOffset;
import static edu.tecnopotify.swing.CrearListaReproduccionJInternalFrame.xOffset;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author menan
 */
public class PublicarListaJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PublicarListaJInternalFrame
     */
    IControlador crl;
    String nick;
    String nombreLista;
        
    public PublicarListaJInternalFrame() {
        super("Publicar Lista Reproduccion",
                true, //resizable
                true, //closable
                true, //maximizable
                true);//iconifiable
        //...Create the GUI and put it in the window...
        //...Then set the window size or call pack...
        this.setTitle("Publicar lista de reproducción");
        //Set the window's location.
        setLocation(xOffset * openFrameCount, yOffset * openFrameCount);
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        crl = fabrica.getInstancia();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNickName = new javax.swing.JLabel();
        jComboBoxNickname = new javax.swing.JComboBox();
        jButtonConfirmarCliente = new javax.swing.JButton();
        jLabelListasRepr = new javax.swing.JLabel();
        jComboBoxNombreListas = new javax.swing.JComboBox();
        jButtonConfirmarLista = new javax.swing.JButton();

        jLabelNickName.setText("NickName");

        jButtonConfirmarCliente.setText("Confirmar");
        jButtonConfirmarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarClienteActionPerformed(evt);
            }
        });

        jLabelListasRepr.setText("Listas de Reproduccion");

        jComboBoxNombreListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNombreListasActionPerformed(evt);
            }
        });

        jButtonConfirmarLista.setText("Confirmar");
        jButtonConfirmarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelListasRepr)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNickName)
                                .addGap(38, 38, 38)
                                .addComponent(jComboBoxNickname, 0, 107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBoxNombreListas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonConfirmarCliente)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonConfirmarLista)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNickName)
                    .addComponent(jComboBoxNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmarCliente))
                .addGap(18, 18, 18)
                .addComponent(jLabelListasRepr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNombreListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmarLista))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarClienteActionPerformed
        // TODO add your handling code here:
        List<Cliente> clientes = crl.listarClientes();
        Iterator<Cliente> it = clientes.iterator();
        while (it.hasNext()) {
            jComboBoxNickname.addItem(it.next().getNickname());
        }
        nick = jComboBoxNickname.getSelectedItem().toString();        
    }//GEN-LAST:event_jButtonConfirmarClienteActionPerformed

    private void jButtonConfirmarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarListaActionPerformed
        // TODO add your handling code here:
        Map<String, ListaParticular> listas = (Map<String, ListaParticular>) crl.seleccionarCliente(nick).listasReprParticular;
        
        Iterator<ListaParticular> it = listas.values().iterator();
        while (it.hasNext()) {
            jComboBoxNombreListas.addItem(it.next().getNombre());
        }
        nombreLista = jComboBoxNombreListas.getSelectedItem().toString();
        crl.publicarLista(nick, nombreLista);
        JOptionPane.showMessageDialog(this, "Lista Publicada con éxito", "Publicar lista de reproducción", JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_jButtonConfirmarListaActionPerformed

    private void jComboBoxNombreListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNombreListasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNombreListasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarCliente;
    private javax.swing.JButton jButtonConfirmarLista;
    private javax.swing.JComboBox<String> jComboBoxNickname;
    private javax.swing.JComboBox<String> jComboBoxNombreListas;
    private javax.swing.JLabel jLabelListasRepr;
    private javax.swing.JLabel jLabelNickName;
    // End of variables declaration//GEN-END:variables
}
