/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.tecnopotify.swing;

import edu.tecnopotify.entidades.Cliente;
import edu.tecnopotify.entidades.ListaParticular;
import edu.tecnopotify.entidades.ListaReproduccion;
import edu.tecnopotify.fabrica.Fabrica;
import edu.tecnopotify.interfaces.IControlador;
import static edu.tecnopotify.swing.AltaClienteJInternalFrame.openFrameCount;
import static edu.tecnopotify.swing.AltaClienteJInternalFrame.yOffset;
import static edu.tecnopotify.swing.CrearListaReproduccionJInternalFrame.xOffset;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author menan
 */
public class PublicarListaJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PublicarListaJInternalFrame
     */
    IControlador crl;

    public PublicarListaJInternalFrame() {
        super("Publicar Lista Reproduccion",
                true, //resizable
                true, //closable
                true, //maximizable
                true);//iconifiable
        //...Create the GUI and put it in the window...
        //...Then set the window size or call pack...
        this.setTitle("Publicar lista de reproducción");
        //Set the window's location.
        setLocation(xOffset * openFrameCount, yOffset * openFrameCount);
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        crl = fabrica.getInstancia();
        cargarComboClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNickName = new javax.swing.JLabel();
        jComboBoxNickname = new javax.swing.JComboBox();
        jLabelListasRepr = new javax.swing.JLabel();
        jComboBoxNombreListas = new javax.swing.JComboBox();
        jButtonConfirmarLista = new javax.swing.JButton();
        jTextEstado = new javax.swing.JTextField();

        jLabelNickName.setText("NickName");

        jComboBoxNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNicknameActionPerformed(evt);
            }
        });

        jLabelListasRepr.setText("Listas de Reproduccion");

        jComboBoxNombreListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNombreListasActionPerformed(evt);
            }
        });

        jButtonConfirmarLista.setText("Cambiar estado");
        jButtonConfirmarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarListaActionPerformed(evt);
            }
        });

        jTextEstado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelListasRepr)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNickName)
                                .addGap(38, 38, 38)
                                .addComponent(jComboBoxNickname, 0, 90, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxNombreListas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButtonConfirmarLista)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNickName)
                    .addComponent(jComboBoxNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelListasRepr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNombreListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmarLista)
                    .addComponent(jTextEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarListaActionPerformed
        // TODO add your handling code here:
        crl.publicarLista(jComboBoxNickname.getSelectedItem().toString(),
                jComboBoxNombreListas.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, "Lista Publicada con éxito", "Publicar lista de reproducción", JOptionPane.INFORMATION_MESSAGE);
        estadoLista();
    }//GEN-LAST:event_jButtonConfirmarListaActionPerformed

    private void jComboBoxNombreListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNombreListasActionPerformed
        // TODO add your handling code here:
        estadoLista();
    }//GEN-LAST:event_jComboBoxNombreListasActionPerformed

    private void jComboBoxNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNicknameActionPerformed
        // TODO add your handling code here:
        cargarComboListas();
    }//GEN-LAST:event_jComboBoxNicknameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarLista;
    private javax.swing.JComboBox<String> jComboBoxNickname;
    private javax.swing.JComboBox<String> jComboBoxNombreListas;
    private javax.swing.JLabel jLabelListasRepr;
    private javax.swing.JLabel jLabelNickName;
    private javax.swing.JTextField jTextEstado;
    // End of variables declaration//GEN-END:variables

    private void cargarComboClientes() {
        jComboBoxNickname.removeAll();
        List<Cliente> clientes = crl.listarClientes();
        Iterator<Cliente> it = clientes.iterator();
        while (it.hasNext()) {
            jComboBoxNickname.addItem(it.next().getNickname());
        }
    }

    private void cargarComboListas() {
        String nick;
        jComboBoxNombreListas.removeAll();
        nick = jComboBoxNickname.getSelectedItem().toString();
        List< ListaParticular> listas = crl.seleccionarCliente(nick).getListasReprParticular();
        Iterator<ListaParticular> it = listas.iterator();
        while (it.hasNext()) {
            jComboBoxNombreListas.addItem(it.next().getNombre());
        }
    }

    private void estadoLista()
    {
        ListaParticular lRepro = (ListaParticular) crl.getlr(jComboBoxNombreListas.getSelectedItem().toString());
        if (lRepro.isEsPrivada()) {
            jTextEstado.setText("Privada");
        } else {
            jTextEstado.setText("Publica");
        }        
    }
}
