/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.tecnopotify.swing;

import edu.tecnopotify.entidades.Cliente;
import edu.tecnopotify.entidades.Usuario;
import edu.tecnopotify.fabrica.Fabrica;
import edu.tecnopotify.interfaces.IControlador;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import edu.tecnopotify.swing.consultarClienteJInternalFrame;

public class SeguirUsuarioJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SeguirUsuarioJInternalFrame
     */
    Fabrica fabrica = Fabrica.getInstance();
    IControlador crl = fabrica.getInstancia();
    private String nick;

    public SeguirUsuarioJInternalFrame() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        crl = fabrica.getInstancia();

        List<Cliente> listCliente = crl.listarClientes();
        Iterator<Cliente> it = listCliente.iterator();
        while (it.hasNext()) {
            jComboCli.addItem(it.next().getNickname());
        }

        List<Usuario> lstUsuarios = crl.listarUsuarios();
        Iterator<Usuario> itUsr = lstUsuarios.iterator();
        while (itUsr.hasNext()) {
            jComboBoxUsuarios.addItem(itUsr.next().getNickname());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuarios = new javax.swing.JLabel();
        jComboBoxUsuarios = new javax.swing.JComboBox();
        jButtonConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboCli = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabelUsuarios.setText("Usuarios");

        jButtonConfirmar.setText("Seguir Usuario");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuarios)
                    .addComponent(jLabel1))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jComboBoxUsuarios, 0, 165, Short.MAX_VALUE)
                    .addComponent(jComboCli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jComboCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuarios)
                    .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonConfirmar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        if (jComboCli.getSelectedItem() != null
                && jComboBoxUsuarios.getSelectedItem() != null) {
            crl.seguirUsuario(jComboCli.getSelectedItem().toString(),
                    jComboBoxUsuarios.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Operacion realizada", "Seguir Usuario", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente y un seguidor");
        }
    
    }//GEN-LAST:event_jButtonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxUsuarios;
    private javax.swing.JComboBox<String> jComboCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUsuarios;
    // End of variables declaration//GEN-END:variables
}
